### ISSUE TITLE
Only left side of menu is active

### ISSUE THREAD

**Issue by xyrer** [ITechRoof/ITRAirSideMenu#2]
When implementing, only the most left side of the menu reacts to tap, the demo is the only one that works, trying to replicate how it does that is unclear, the storyboard reveals nothing of significance.

**Comment by ghost** [comment]
Fixed it, I put [self.view bringSubviewToFront:self.menuViewContainer]; at the end of showLeftMenuViewController and viceversa

**Comment by ITechRoof** [comment]
@gparrado : Your fix was not the exact fix. Because by bringing menucontainer to front of the view, Contentviewcontroller pan wont happen as it can never listen to his action. Whenever menu container is shown, we are adding content button on top of content view container. By clicking on this, user can jus close the menu container without changing any menu selection. User can also close the menu by panning the content view container. Both this case will never happen if menu container is brought as top view. Clicking on content view container will be taken as menu selection in this case.

**Comment by ghost** [comment]
You're right, that fix only applies to certain use case, but then the problem persists, the menu is not accessible as the content view is on top even as it seems as it's on the far right, in reality it's still covering almost the whole screen.

**Comment by khushDesai** [comment]
is there issue solved or not ? i have faced same issue that only left hand's side of menu is work.
